import type { ConversionProfile } from '../types';

export const BUILTIN_PROFILES: ConversionProfile[] = [
  // ════════════════════════════════════════════════════════════════
  //  WEB & SOCIAL
  // ════════════════════════════════════════════════════════════════

  // YouTube
  {
    id: 'yt-4k',
    name: 'YouTube 4K',
    category: 'web-social',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 16,
    preset: 'slow',
    scale: '3840x2160',
    audioBitrate: '320k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 3840×2160',
  },
  {
    id: 'yt-1440p',
    name: 'YouTube 1440p',
    category: 'web-social',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 17,
    preset: 'slow',
    scale: '2560x1440',
    audioBitrate: '256k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 2560×1440',
  },
  {
    id: 'yt-1080p',
    name: 'YouTube 1080p',
    category: 'web-social',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 18,
    preset: 'medium',
    scale: '1920x1080',
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1920×1080',
  },
  {
    id: 'yt-720p',
    name: 'YouTube 720p',
    category: 'web-social',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 20,
    preset: 'medium',
    scale: '1280x720',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1280×720',
  },
  {
    id: 'yt-480p',
    name: 'YouTube 480p',
    category: 'web-social',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 23,
    preset: 'medium',
    scale: '854x480',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 854×480',
  },
  {
    id: 'yt-360p',
    name: 'YouTube 360p',
    category: 'web-social',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 26,
    preset: 'fast',
    scale: '640x360',
    audioBitrate: '96k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 640×360',
  },
  {
    id: 'yt-shorts-4k',
    name: 'YouTube Shorts 4K',
    category: 'web-social',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 16,
    preset: 'slow',
    scale: '2160x3840',
    audioBitrate: '256k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 2160×3840 vertical',
  },
  {
    id: 'yt-shorts-1080p',
    name: 'YouTube Shorts 1080p',
    category: 'web-social',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 18,
    preset: 'medium',
    scale: '1080x1920',
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1080×1920 vertical',
  },

  // Instagram
  {
    id: 'ig-reel-1080p',
    name: 'Instagram Reel 1080p',
    category: 'web-social',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 20,
    preset: 'medium',
    scale: '1080x1920',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1080×1920 vertical',
  },
  {
    id: 'ig-reel-720p',
    name: 'Instagram Reel 720p',
    category: 'web-social',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 23,
    preset: 'medium',
    scale: '720x1280',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 720×1280 vertical',
  },
  {
    id: 'ig-story-1080p',
    name: 'Instagram Story 1080p',
    category: 'web-social',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 20,
    preset: 'medium',
    scale: '1080x1920',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1080×1920 vertical',
  },
  {
    id: 'ig-post-1080p',
    name: 'Instagram Post 1080p',
    category: 'web-social',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 20,
    preset: 'medium',
    scale: '1080x1080',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1080×1080 square',
  },

  // TikTok
  {
    id: 'tiktok-1080p',
    name: 'TikTok 1080p',
    category: 'web-social',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 20,
    preset: 'medium',
    scale: '1080x1920',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1080×1920 vertical',
  },
  {
    id: 'tiktok-720p',
    name: 'TikTok 720p',
    category: 'web-social',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 23,
    preset: 'medium',
    scale: '720x1280',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 720×1280 vertical',
  },

  // Facebook
  {
    id: 'fb-1080p',
    name: 'Facebook 1080p',
    category: 'web-social',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 20,
    preset: 'medium',
    scale: '1920x1080',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1920×1080',
  },
  {
    id: 'fb-720p',
    name: 'Facebook 720p',
    category: 'web-social',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 23,
    preset: 'medium',
    scale: '1280x720',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1280×720',
  },
  {
    id: 'fb-4k',
    name: 'Facebook 4K',
    category: 'web-social',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 16,
    preset: 'slow',
    scale: '3840x2160',
    audioBitrate: '256k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 3840×2160',
  },

  // X / Twitter
  {
    id: 'x-1080p',
    name: 'X 1080p',
    category: 'web-social',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 20,
    preset: 'medium',
    scale: '1920x1080',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1920×1080',
  },
  {
    id: 'x-720p',
    name: 'X 720p',
    category: 'web-social',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 23,
    preset: 'medium',
    scale: '1280x720',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1280×720',
  },

  // ════════════════════════════════════════════════════════════════
  //  DEVICES
  // ════════════════════════════════════════════════════════════════

  // Apple
  {
    id: 'iphone-4k',
    name: 'iPhone 4K',
    category: 'devices',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 18,
    preset: 'medium',
    scale: '3840x2160',
    audioBitrate: '256k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 3840×2160',
  },
  {
    id: 'iphone-1080p',
    name: 'iPhone 1080p',
    category: 'devices',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 20,
    preset: 'medium',
    scale: '1920x1080',
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1920×1080',
  },
  {
    id: 'iphone-720p',
    name: 'iPhone 720p',
    category: 'devices',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 23,
    preset: 'medium',
    scale: '1280x720',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1280×720',
  },
  {
    id: 'ipad-4k',
    name: 'iPad 4K',
    category: 'devices',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 18,
    preset: 'medium',
    scale: '3840x2160',
    audioBitrate: '256k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 3840×2160',
  },
  {
    id: 'ipad-1080p',
    name: 'iPad 1080p',
    category: 'devices',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 20,
    preset: 'medium',
    scale: '1920x1080',
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1920×1080',
  },
  {
    id: 'appletv-4k',
    name: 'Apple TV 4K',
    category: 'devices',
    container: 'mp4',
    videoCodec: 'libx265',
    audioCodec: 'aac',
    crf: 20,
    preset: 'medium',
    scale: '3840x2160',
    audioBitrate: '256k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Modern',
    description: 'MP4 / H.265 / AAC — 3840×2160',
  },
  {
    id: 'appletv-hd',
    name: 'Apple TV HD',
    category: 'devices',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 20,
    preset: 'medium',
    scale: '1920x1080',
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1920×1080',
  },

  // Android
  {
    id: 'android-4k',
    name: 'Android 4K',
    category: 'devices',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 18,
    preset: 'medium',
    scale: '3840x2160',
    audioBitrate: '256k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 3840×2160',
  },
  {
    id: 'android-1080p',
    name: 'Android 1080p',
    category: 'devices',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 20,
    preset: 'medium',
    scale: '1920x1080',
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1920×1080',
  },
  {
    id: 'android-720p',
    name: 'Android 720p',
    category: 'devices',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 23,
    preset: 'medium',
    scale: '1280x720',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1280×720',
  },
  {
    id: 'android-compat',
    name: 'Android Compatibility',
    category: 'devices',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 23,
    preset: 'fast',
    scale: '1280x720',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — broad Android support',
  },
  {
    id: 'android-hevc',
    name: 'Android HEVC',
    category: 'devices',
    container: 'mp4',
    videoCodec: 'libx265',
    audioCodec: 'aac',
    crf: 22,
    preset: 'medium',
    scale: '1920x1080',
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Modern',
    description: 'MP4 / H.265 / AAC — 1920×1080',
  },

  // Gaming
  {
    id: 'ps4',
    name: 'PlayStation 4',
    category: 'devices',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 18,
    preset: 'medium',
    scale: '1920x1080',
    audioBitrate: '256k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1920×1080',
  },
  {
    id: 'ps5',
    name: 'PlayStation 5',
    category: 'devices',
    container: 'mp4',
    videoCodec: 'libx265',
    audioCodec: 'aac',
    crf: 18,
    preset: 'medium',
    scale: '3840x2160',
    audioBitrate: '320k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Modern',
    description: 'MP4 / H.265 / AAC — 3840×2160',
  },
  {
    id: 'xbox-one',
    name: 'Xbox One',
    category: 'devices',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 18,
    preset: 'medium',
    scale: '1920x1080',
    audioBitrate: '256k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1920×1080',
  },
  {
    id: 'xbox-series',
    name: 'Xbox Series X/S',
    category: 'devices',
    container: 'mp4',
    videoCodec: 'libx265',
    audioCodec: 'aac',
    crf: 18,
    preset: 'medium',
    scale: '3840x2160',
    audioBitrate: '320k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Modern',
    description: 'MP4 / H.265 / AAC — 3840×2160',
  },
  {
    id: 'switch',
    name: 'Nintendo Switch',
    category: 'devices',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 20,
    preset: 'medium',
    scale: '1920x1080',
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1920×1080',
  },

  // ════════════════════════════════════════════════════════════════
  //  VIDEO (General)
  // ════════════════════════════════════════════════════════════════

  // MP4
  {
    id: 'mp4-max-compat',
    name: 'MP4 – Maximum Compatibility',
    category: 'video',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 23,
    preset: 'medium',
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — widest device support',
  },
  {
    id: 'mp4-hq',
    name: 'MP4 – High Quality',
    category: 'video',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 16,
    preset: 'slow',
    audioBitrate: '320k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — visually lossless',
  },
  {
    id: 'mp4-small',
    name: 'MP4 – Small File',
    category: 'video',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 28,
    preset: 'fast',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — compact size',
  },
  {
    id: 'mp4-720p',
    name: 'MP4 – 720p',
    category: 'video',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 23,
    preset: 'medium',
    scale: '1280x720',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1280×720',
  },
  {
    id: 'mp4-1080p',
    name: 'MP4 – 1080p',
    category: 'video',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 20,
    preset: 'medium',
    scale: '1920x1080',
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 1920×1080',
  },
  {
    id: 'mp4-1440p',
    name: 'MP4 – 1440p',
    category: 'video',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 18,
    preset: 'slow',
    scale: '2560x1440',
    audioBitrate: '256k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 2560×1440',
  },
  {
    id: 'mp4-4k',
    name: 'MP4 – 4K',
    category: 'video',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 16,
    preset: 'slow',
    scale: '3840x2160',
    audioBitrate: '320k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP4 / H.264 / AAC — 3840×2160',
  },
  {
    id: 'mp4-h265',
    name: 'MP4 – H.265',
    category: 'video',
    container: 'mp4',
    videoCodec: 'libx265',
    audioCodec: 'aac',
    crf: 22,
    preset: 'medium',
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Modern',
    description: 'MP4 / H.265 / AAC — better compression',
  },
  {
    id: 'mp4-av1',
    name: 'MP4 – AV1',
    category: 'video',
    container: 'mp4',
    videoCodec: 'libsvtav1',
    audioCodec: 'aac',
    crf: 30,
    preset: '6',
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Modern',
    description: 'MP4 / AV1 / AAC — next-gen compression',
  },

  // MKV
  {
    id: 'mkv-universal',
    name: 'MKV – Universal',
    category: 'video',
    container: 'mkv',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 20,
    preset: 'medium',
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MKV / H.264 / AAC — flexible container',
  },
  {
    id: 'mkv-hq',
    name: 'MKV – High Quality',
    category: 'video',
    container: 'mkv',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 16,
    preset: 'slow',
    audioBitrate: '320k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MKV / H.264 / AAC — visually lossless',
  },
  {
    id: 'mkv-h265',
    name: 'MKV – H.265',
    category: 'video',
    container: 'mkv',
    videoCodec: 'libx265',
    audioCodec: 'aac',
    crf: 22,
    preset: 'medium',
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Modern',
    description: 'MKV / H.265 / AAC — efficient compression',
  },
  {
    id: 'mkv-av1',
    name: 'MKV – AV1',
    category: 'video',
    container: 'mkv',
    videoCodec: 'libsvtav1',
    audioCodec: 'aac',
    crf: 30,
    preset: '6',
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Modern',
    description: 'MKV / AV1 / AAC — next-gen codec',
  },
  {
    id: 'mkv-vp9',
    name: 'MKV – VP9',
    category: 'video',
    container: 'mkv',
    videoCodec: 'libvpx-vp9',
    audioCodec: 'libopus',
    crf: 30,
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Modern',
    description: 'MKV / VP9 / Opus — open web codec',
  },
  {
    id: 'mkv-lossless',
    name: 'MKV – Lossless',
    category: 'video',
    container: 'mkv',
    videoCodec: 'libx264',
    audioCodec: 'flac',
    extraArgs: ['-crf', '0'],
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Modern',
    description: 'MKV / H.264 Lossless / FLAC',
  },

  // MOV
  {
    id: 'mov-h264',
    name: 'MOV – H.264',
    category: 'video',
    container: 'mov',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 20,
    preset: 'medium',
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'MOV / H.264 / AAC — Apple ecosystem',
  },
  {
    id: 'mov-hevc',
    name: 'MOV – HEVC',
    category: 'video',
    container: 'mov',
    videoCodec: 'libx265',
    audioCodec: 'aac',
    crf: 22,
    preset: 'medium',
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Modern',
    description: 'MOV / H.265 / AAC — efficient Apple format',
  },

  // WebM
  {
    id: 'webm-vp8',
    name: 'WebM – VP8',
    category: 'video',
    container: 'webm',
    videoCodec: 'libvpx',
    audioCodec: 'libvorbis',
    crf: 10,
    audioBitrate: '192k',
    builtin: true,
    compatibility: 'Broad',
    description: 'WebM / VP8 / Vorbis — legacy web format',
  },
  {
    id: 'webm-vp9',
    name: 'WebM – VP9',
    category: 'video',
    container: 'webm',
    videoCodec: 'libvpx-vp9',
    audioCodec: 'libopus',
    crf: 30,
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Modern',
    description: 'WebM / VP9 / Opus — modern web format',
  },
  {
    id: 'webm-av1',
    name: 'WebM – AV1',
    category: 'video',
    container: 'webm',
    videoCodec: 'libsvtav1',
    audioCodec: 'libopus',
    crf: 30,
    preset: '6',
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Modern',
    description: 'WebM / AV1 / Opus — next-gen web format',
  },
  {
    id: 'webm-small',
    name: 'WebM – Small File',
    category: 'video',
    container: 'webm',
    videoCodec: 'libvpx-vp9',
    audioCodec: 'libopus',
    crf: 35,
    audioBitrate: '96k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Modern',
    description: 'WebM / VP9 / Opus — compact size',
  },
  {
    id: 'webm-hq',
    name: 'WebM – High Quality',
    category: 'video',
    container: 'webm',
    videoCodec: 'libvpx-vp9',
    audioCodec: 'libopus',
    crf: 15,
    audioBitrate: '256k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Modern',
    description: 'WebM / VP9 / Opus — visually lossless',
  },

  // AVI
  {
    id: 'avi-mpeg4',
    name: 'AVI – MPEG-4',
    category: 'video',
    container: 'avi',
    videoCodec: 'mpeg4',
    audioCodec: 'libmp3lame',
    audioBitrate: '192k',
    builtin: true,
    compatibility: 'Broad',
    description: 'AVI / MPEG-4 / MP3 — legacy format',
  },
  {
    id: 'avi-h264',
    name: 'AVI – H.264',
    category: 'video',
    container: 'avi',
    videoCodec: 'libx264',
    audioCodec: 'libmp3lame',
    crf: 20,
    audioBitrate: '192k',
    pixelFormat: 'yuv420p',
    builtin: true,
    compatibility: 'Broad',
    description: 'AVI / H.264 / MP3',
  },
  {
    id: 'avi-mjpeg',
    name: 'AVI – MJPEG',
    category: 'video',
    container: 'avi',
    videoCodec: 'mjpeg',
    audioCodec: 'libmp3lame',
    audioBitrate: '192k',
    builtin: true,
    compatibility: 'Broad',
    description: 'AVI / Motion JPEG / MP3 — editing friendly',
  },

  // MPEG
  {
    id: 'mpeg1',
    name: 'MPEG-1 Video',
    category: 'video',
    container: 'mpg',
    videoCodec: 'mpeg1video',
    audioCodec: 'libmp3lame',
    audioBitrate: '192k',
    builtin: true,
    compatibility: 'Broad',
    description: 'MPG / MPEG-1 / MP3 — VCD compatible',
  },
  {
    id: 'mpeg2',
    name: 'MPEG-2 Video',
    category: 'video',
    container: 'mpg',
    videoCodec: 'mpeg2video',
    audioCodec: 'libmp2',
    audioBitrate: '192k',
    builtin: true,
    compatibility: 'Broad',
    description: 'MPG / MPEG-2 / MP2 — DVD compatible',
  },

  // ════════════════════════════════════════════════════════════════
  //  PROFESSIONAL
  // ════════════════════════════════════════════════════════════════

  // Apple ProRes
  {
    id: 'prores-proxy',
    name: 'ProRes Proxy',
    category: 'professional',
    container: 'mov',
    videoCodec: 'prores',
    audioCodec: 'aac',
    extraArgs: ['-profile:v', '0'],
    audioBitrate: '256k',
    builtin: true,
    compatibility: 'Professional',
    description: 'MOV / ProRes Proxy — lowest quality, smallest files',
  },
  {
    id: 'prores-422-lt',
    name: 'ProRes 422 LT',
    category: 'professional',
    container: 'mov',
    videoCodec: 'prores',
    audioCodec: 'aac',
    extraArgs: ['-profile:v', '1'],
    audioBitrate: '256k',
    builtin: true,
    compatibility: 'Professional',
    description: 'MOV / ProRes 422 LT — lightweight 422',
  },
  {
    id: 'prores-422',
    name: 'ProRes 422',
    category: 'professional',
    container: 'mov',
    videoCodec: 'prores',
    audioCodec: 'aac',
    extraArgs: ['-profile:v', '2'],
    audioBitrate: '320k',
    builtin: true,
    compatibility: 'Professional',
    description: 'MOV / ProRes 422 — standard editing codec',
  },
  {
    id: 'prores-422-hq',
    name: 'ProRes 422 HQ',
    category: 'professional',
    container: 'mov',
    videoCodec: 'prores',
    audioCodec: 'aac',
    extraArgs: ['-profile:v', '3'],
    audioBitrate: '320k',
    builtin: true,
    compatibility: 'Professional',
    description: 'MOV / ProRes 422 HQ — high quality 422',
  },
  {
    id: 'prores-4444',
    name: 'ProRes 4444',
    category: 'professional',
    container: 'mov',
    videoCodec: 'prores',
    audioCodec: 'aac',
    extraArgs: ['-profile:v', '4'],
    audioBitrate: '320k',
    builtin: true,
    compatibility: 'Professional',
    description: 'MOV / ProRes 4444 — alpha channel support',
  },
  {
    id: 'prores-4444-xq',
    name: 'ProRes 4444 XQ',
    category: 'professional',
    container: 'mov',
    videoCodec: 'prores',
    audioCodec: 'aac',
    extraArgs: ['-profile:v', '5'],
    audioBitrate: '320k',
    builtin: true,
    compatibility: 'Professional',
    description: 'MOV / ProRes 4444 XQ — highest quality ProRes',
  },

  // Avid DNx
  {
    id: 'dnxhr-lb',
    name: 'DNxHR LB',
    category: 'professional',
    container: 'mxf',
    videoCodec: 'dnxhd',
    audioCodec: 'pcm_s24le',
    extraArgs: ['-b:v', '36M', '-pix_fmt', 'yuv422p'],
    builtin: true,
    compatibility: 'Professional',
    description: 'MXF / DNxHR LB — low bandwidth',
  },
  {
    id: 'dnxhr-sq',
    name: 'DNxHR SQ',
    category: 'professional',
    container: 'mxf',
    videoCodec: 'dnxhd',
    audioCodec: 'pcm_s24le',
    extraArgs: ['-b:v', '75M', '-pix_fmt', 'yuv422p'],
    builtin: true,
    compatibility: 'Professional',
    description: 'MXF / DNxHR SQ — standard quality',
  },
  {
    id: 'dnxhr-hq',
    name: 'DNxHR HQ',
    category: 'professional',
    container: 'mxf',
    videoCodec: 'dnxhd',
    audioCodec: 'pcm_s24le',
    extraArgs: ['-b:v', '110M', '-pix_fmt', 'yuv422p'],
    builtin: true,
    compatibility: 'Professional',
    description: 'MXF / DNxHR HQ — high quality',
  },
  {
    id: 'dnxhr-hqx',
    name: 'DNxHR HQX',
    category: 'professional',
    container: 'mxf',
    videoCodec: 'dnxhd',
    audioCodec: 'pcm_s24le',
    extraArgs: ['-b:v', '110M', '-pix_fmt', 'yuv422p10le'],
    builtin: true,
    compatibility: 'Professional',
    description: 'MXF / DNxHR HQX — 10-bit high quality',
  },
  {
    id: 'dnxhr-444',
    name: 'DNxHR 444',
    category: 'professional',
    container: 'mxf',
    videoCodec: 'dnxhd',
    audioCodec: 'pcm_s24le',
    extraArgs: ['-b:v', '130M', '-pix_fmt', 'yuv444p10le'],
    builtin: true,
    compatibility: 'Professional',
    description: 'MXF / DNxHR 444 — full chroma, 10-bit',
  },

  // CineForm
  {
    id: 'cineform-low',
    name: 'CineForm Low',
    category: 'professional',
    container: 'mov',
    videoCodec: 'cfhd',
    audioCodec: 'aac',
    audioBitrate: '192k',
    builtin: true,
    compatibility: 'Professional',
    description: 'MOV / CineForm — low compression',
  },
  {
    id: 'cineform-high',
    name: 'CineForm High',
    category: 'professional',
    container: 'mov',
    videoCodec: 'cfhd',
    audioCodec: 'aac',
    audioBitrate: '256k',
    builtin: true,
    compatibility: 'Professional',
    description: 'MOV / CineForm — high quality',
  },

  // Lossless / Archival
  {
    id: 'ffv1-mkv',
    name: 'FFV1 Lossless',
    category: 'professional',
    container: 'mkv',
    videoCodec: 'ffv1',
    audioCodec: 'flac',
    builtin: true,
    compatibility: 'Professional',
    description: 'MKV / FFV1 / FLAC — mathematically lossless',
  },
  {
    id: 'ffv1-10bit',
    name: 'FFV1 10-bit',
    category: 'professional',
    container: 'mkv',
    videoCodec: 'ffv1',
    audioCodec: 'flac',
    extraArgs: ['-level', '3', '-slicecrc', '1'],
    pixelFormat: 'yuv422p10le',
    builtin: true,
    compatibility: 'Professional',
    description: 'MKV / FFV1 10-bit / FLAC — archival grade',
  },
  {
    id: 'huffyuv',
    name: 'HuffYUV',
    category: 'professional',
    container: 'avi',
    videoCodec: 'huffyuv',
    audioCodec: 'pcm_s16le',
    builtin: true,
    compatibility: 'Professional',
    description: 'AVI / HuffYUV / PCM — fast lossless',
  },
  {
    id: 'uncompressed-yuv',
    name: 'Uncompressed YUV',
    category: 'professional',
    container: 'avi',
    videoCodec: 'rawvideo',
    audioCodec: 'pcm_s16le',
    extraArgs: ['-pix_fmt', 'yuv420p'],
    builtin: true,
    compatibility: 'Professional',
    description: 'AVI / Raw YUV / PCM — no compression',
  },

  // ════════════════════════════════════════════════════════════════
  //  STREAMING
  // ════════════════════════════════════════════════════════════════

  {
    id: 'hls-1080p',
    name: 'HLS 1080p',
    category: 'streaming',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 20,
    preset: 'medium',
    scale: '1920x1080',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    extraArgs: ['-hls_time', '6', '-hls_list_size', '0'],
    builtin: true,
    compatibility: 'Broad',
    description: 'HLS 1080p — HTTP Live Streaming segments',
  },
  {
    id: 'hls-720p',
    name: 'HLS 720p',
    category: 'streaming',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 23,
    preset: 'medium',
    scale: '1280x720',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    extraArgs: ['-hls_time', '6', '-hls_list_size', '0'],
    builtin: true,
    compatibility: 'Broad',
    description: 'HLS 720p — HTTP Live Streaming segments',
  },
  {
    id: 'hls-480p',
    name: 'HLS 480p',
    category: 'streaming',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 26,
    preset: 'fast',
    scale: '854x480',
    audioBitrate: '96k',
    pixelFormat: 'yuv420p',
    extraArgs: ['-hls_time', '6', '-hls_list_size', '0'],
    builtin: true,
    compatibility: 'Broad',
    description: 'HLS 480p — HTTP Live Streaming segments',
  },
  {
    id: 'dash-1080p',
    name: 'DASH 1080p',
    category: 'streaming',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 20,
    preset: 'medium',
    scale: '1920x1080',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    extraArgs: ['-f', 'dash', '-seg_duration', '6'],
    builtin: true,
    compatibility: 'Broad',
    description: 'DASH 1080p — MPEG-DASH segments',
  },
  {
    id: 'dash-720p',
    name: 'DASH 720p',
    category: 'streaming',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    crf: 23,
    preset: 'medium',
    scale: '1280x720',
    audioBitrate: '128k',
    pixelFormat: 'yuv420p',
    extraArgs: ['-f', 'dash', '-seg_duration', '6'],
    builtin: true,
    compatibility: 'Broad',
    description: 'DASH 720p — MPEG-DASH segments',
  },

  // ════════════════════════════════════════════════════════════════
  //  AUDIO
  // ════════════════════════════════════════════════════════════════

  // Lossy
  {
    id: 'mp3-320',
    name: 'MP3 – 320 kbps',
    category: 'audio',
    container: 'mp3',
    videoCodec: 'copy',
    audioCodec: 'libmp3lame',
    audioBitrate: '320k',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP3 CBR 320 kbps — highest lossy quality',
  },
  {
    id: 'mp3-256',
    name: 'MP3 – 256 kbps',
    category: 'audio',
    container: 'mp3',
    videoCodec: 'copy',
    audioCodec: 'libmp3lame',
    audioBitrate: '256k',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP3 CBR 256 kbps',
  },
  {
    id: 'mp3-192',
    name: 'MP3 – 192 kbps',
    category: 'audio',
    container: 'mp3',
    videoCodec: 'copy',
    audioCodec: 'libmp3lame',
    audioBitrate: '192k',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP3 CBR 192 kbps',
  },
  {
    id: 'mp3-128',
    name: 'MP3 – 128 kbps',
    category: 'audio',
    container: 'mp3',
    videoCodec: 'copy',
    audioCodec: 'libmp3lame',
    audioBitrate: '128k',
    builtin: true,
    compatibility: 'Broad',
    description: 'MP3 CBR 128 kbps — smallest',
  },
  {
    id: 'aac-320',
    name: 'AAC – 320 kbps',
    category: 'audio',
    container: 'm4a',
    videoCodec: 'copy',
    audioCodec: 'aac',
    audioBitrate: '320k',
    builtin: true,
    compatibility: 'Broad',
    description: 'AAC CBR 320 kbps',
  },
  {
    id: 'aac-256',
    name: 'AAC – 256 kbps',
    category: 'audio',
    container: 'm4a',
    videoCodec: 'copy',
    audioCodec: 'aac',
    audioBitrate: '256k',
    builtin: true,
    compatibility: 'Broad',
    description: 'AAC CBR 256 kbps',
  },
  {
    id: 'aac-192',
    name: 'AAC – 192 kbps',
    category: 'audio',
    container: 'm4a',
    videoCodec: 'copy',
    audioCodec: 'aac',
    audioBitrate: '192k',
    builtin: true,
    compatibility: 'Broad',
    description: 'AAC CBR 192 kbps',
  },
  {
    id: 'aac-128',
    name: 'AAC – 128 kbps',
    category: 'audio',
    container: 'm4a',
    videoCodec: 'copy',
    audioCodec: 'aac',
    audioBitrate: '128k',
    builtin: true,
    compatibility: 'Broad',
    description: 'AAC CBR 128 kbps',
  },
  {
    id: 'opus-160',
    name: 'Opus – 160 kbps',
    category: 'audio',
    container: 'opus',
    videoCodec: 'copy',
    audioCodec: 'libopus',
    audioBitrate: '160k',
    builtin: true,
    compatibility: 'Modern',
    description: 'Opus CBR 160 kbps — best quality/size',
  },
  {
    id: 'opus-128',
    name: 'Opus – 128 kbps',
    category: 'audio',
    container: 'opus',
    videoCodec: 'copy',
    audioCodec: 'libopus',
    audioBitrate: '128k',
    builtin: true,
    compatibility: 'Modern',
    description: 'Opus CBR 128 kbps',
  },
  {
    id: 'vorbis-hq',
    name: 'Vorbis – High Quality',
    category: 'audio',
    container: 'ogg',
    videoCodec: 'copy',
    audioCodec: 'libvorbis',
    extraArgs: ['-q:a', '8'],
    builtin: true,
    compatibility: 'Modern',
    description: 'Vorbis Q8 — open high quality',
  },

  // Lossless
  {
    id: 'flac',
    name: 'FLAC',
    category: 'audio',
    container: 'flac',
    videoCodec: 'copy',
    audioCodec: 'flac',
    builtin: true,
    compatibility: 'Broad',
    description: 'FLAC — open lossless',
  },
  {
    id: 'flac-16',
    name: 'FLAC 16-bit',
    category: 'audio',
    container: 'flac',
    videoCodec: 'copy',
    audioCodec: 'flac',
    extraArgs: ['-sample_fmt', 's16'],
    builtin: true,
    compatibility: 'Broad',
    description: 'FLAC 16-bit — CD quality',
  },
  {
    id: 'flac-24',
    name: 'FLAC 24-bit',
    category: 'audio',
    container: 'flac',
    videoCodec: 'copy',
    audioCodec: 'flac',
    extraArgs: ['-sample_fmt', 's32'],
    builtin: true,
    compatibility: 'Broad',
    description: 'FLAC 24-bit — hi-res audio',
  },
  {
    id: 'alac',
    name: 'ALAC',
    category: 'audio',
    container: 'm4a',
    videoCodec: 'copy',
    audioCodec: 'alac',
    builtin: true,
    compatibility: 'Broad',
    description: 'Apple Lossless — iTunes compatible',
  },
  {
    id: 'wav',
    name: 'WAV PCM',
    category: 'audio',
    container: 'wav',
    videoCodec: 'copy',
    audioCodec: 'pcm_s16le',
    builtin: true,
    compatibility: 'Broad',
    description: 'WAV / PCM S16LE — uncompressed',
  },
  {
    id: 'aiff',
    name: 'AIFF PCM',
    category: 'audio',
    container: 'aiff',
    videoCodec: 'copy',
    audioCodec: 'pcm_s16be',
    builtin: true,
    compatibility: 'Broad',
    description: 'AIFF / PCM S16BE — Apple uncompressed',
  },

  // Dolby
  {
    id: 'ac3',
    name: 'Dolby Digital AC-3',
    category: 'audio',
    container: 'ac3',
    videoCodec: 'copy',
    audioCodec: 'ac3',
    audioBitrate: '384k',
    builtin: true,
    compatibility: 'Broad',
    description: 'Dolby Digital AC-3 — surround sound',
  },
  {
    id: 'eac3',
    name: 'Dolby Digital Plus E-AC-3',
    category: 'audio',
    container: 'eac3',
    videoCodec: 'copy',
    audioCodec: 'eac3',
    audioBitrate: '512k',
    builtin: true,
    compatibility: 'Broad',
    description: 'Dolby Digital Plus — enhanced surround',
  },

  // ════════════════════════════════════════════════════════════════
  //  IMAGES
  // ════════════════════════════════════════════════════════════════

  {
    id: 'jpeg',
    name: 'JPEG',
    category: 'images',
    container: 'jpg',
    videoCodec: 'copy',
    audioCodec: 'copy',
    extraArgs: ['-q:v', '2'],
    builtin: true,
    compatibility: 'Broad',
    description: 'JPEG — universal photo format',
  },
  {
    id: 'png',
    name: 'PNG',
    category: 'images',
    container: 'png',
    videoCodec: 'copy',
    audioCodec: 'copy',
    builtin: true,
    compatibility: 'Broad',
    description: 'PNG — lossless with transparency',
  },
  {
    id: 'webp-img',
    name: 'WebP',
    category: 'images',
    container: 'webp',
    videoCodec: 'copy',
    audioCodec: 'copy',
    builtin: true,
    compatibility: 'Modern',
    description: 'WebP — modern web image format',
  },
  {
    id: 'avif-img',
    name: 'AVIF',
    category: 'images',
    container: 'avif',
    videoCodec: 'copy',
    audioCodec: 'copy',
    builtin: true,
    compatibility: 'Modern',
    description: 'AVIF — next-gen image format',
  },
  {
    id: 'tiff',
    name: 'TIFF',
    category: 'images',
    container: 'tiff',
    videoCodec: 'copy',
    audioCodec: 'copy',
    builtin: true,
    compatibility: 'Broad',
    description: 'TIFF — lossless print format',
  },
  {
    id: 'bmp',
    name: 'BMP',
    category: 'images',
    container: 'bmp',
    videoCodec: 'copy',
    audioCodec: 'copy',
    builtin: true,
    compatibility: 'Broad',
    description: 'BMP — uncompressed bitmap',
  },
  {
    id: 'gif',
    name: 'GIF',
    category: 'images',
    container: 'gif',
    videoCodec: 'copy',
    audioCodec: 'copy',
    builtin: true,
    compatibility: 'Broad',
    description: 'GIF — animated image support',
  },

  // ════════════════════════════════════════════════════════════════
  //  ADVANCED
  // ════════════════════════════════════════════════════════════════

  {
    id: 'raw-yuv',
    name: 'Raw YUV',
    category: 'advanced',
    container: 'avi',
    videoCodec: 'rawvideo',
    audioCodec: 'copy',
    extraArgs: ['-pix_fmt', 'yuv420p'],
    builtin: true,
    compatibility: 'Professional',
    description: 'Raw YUV video — no compression',
  },
  {
    id: 'raw-pcm',
    name: 'Raw PCM Audio',
    category: 'advanced',
    container: 'wav',
    videoCodec: 'copy',
    audioCodec: 'pcm_s16le',
    builtin: true,
    compatibility: 'Professional',
    description: 'Raw PCM S16LE audio',
  },
  {
    id: 'null-output',
    name: 'Null Output',
    category: 'advanced',
    container: 'null',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    extraArgs: ['-f', 'null'],
    builtin: true,
    compatibility: 'Professional',
    description: 'Encode to null — benchmark/test only',
  },
  {
    id: 'custom-ffmpeg',
    name: 'Custom FFmpeg',
    category: 'advanced',
    container: 'mp4',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    builtin: true,
    compatibility: 'Professional',
    description: 'Start from scratch with custom FFmpeg arguments',
  },
];
