export const IPC = {
  SELECT_FILE: 'select-file',
  SELECT_FILES: 'select-files',
  SELECT_OUTPUT: 'select-output',
  GET_MEDIA_INFO: 'get-media-info',
  CONVERT_FILE: 'convert-file',
  CANCEL_CONVERSION: 'cancel-conversion',
  QUEUE_ADD: 'queue-add',
  QUEUE_REMOVE: 'queue-remove',
  QUEUE_LIST: 'queue-list',
  QUEUE_CANCEL_ALL: 'queue-cancel-all',
  PLAYER_OPEN: 'player-open',
  PLAYER_SEEK: 'player-seek',
  PLAYER_CLOSE: 'player-close',
  PLAYER_GET_FRAME: 'player-get-frame',

  CONVERSION_PROGRESS: 'conversion-progress',
  QUEUE_ADDED: 'queue-added',
  QUEUE_REMOVED: 'queue-removed',
  QUEUE_STATUS_CHANGE: 'queue-status-change',
  QUEUE_PROGRESS: 'queue-progress',
  QUEUE_CANCELLED: 'queue-cancelled',
  PLAYER_FRAME: 'player-frame',
} as const;
